"""Lua bridges for dynamic hyprlang sources and hyprctl helper scripts."""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HYPR = ROOT / "config/hyprland"
BRIDGES = HYPR / "lua/bridges.lua"
ENTRY = HYPR / "hyprland.lua"
APPEARANCE = HYPR / "lua/appearance.lua"
MAP_PATH = HYPR / "lua-ownership-map.json"
LIVE_LINK = Path.home() / ".config/hypr/hyprland.conf"
MONITORS_CONF = Path.home() / ".config/hypr/monitors.conf"
GENERATOR = ROOT / "scripts/build-hypr-lua-generated-monitors"
SYNC_PYWAL = ROOT / "scripts/sync-pywal-theme.py"
PHONE = ROOT / "scripts/phone-display.sh"
GUI_E2E = ROOT / "scripts/gui-e2e-display.sh"
APPLY_PYWAL = ROOT / "scripts/apply-pywal-theme.sh"


def _lua_tree() -> str:
    parts = [ENTRY.read_text(), BRIDGES.read_text() if BRIDGES.is_file() else ""]
    parts.extend(path.read_text() for path in sorted((HYPR / "lua").glob("*.lua")))
    generated = HYPR / "lua/generated"
    if generated.is_dir():
        parts.extend(path.read_text() for path in sorted(generated.glob("*.lua")))
    return "\n".join(parts)


def test_every_inventory_source_and_script_line_has_a_concrete_lua_bridge():
    payload = json.loads(MAP_PATH.read_text())
    tree = _lua_tree()
    assert BRIDGES.is_file(), "lua/bridges.lua must own dynamic sources"
    assert 'require("lua.bridges")' in ENTRY.read_text()
    for item in payload["sourced_files"]:
        assert item["lua_api"] in {"generated Lua artifact", "explicit bridge"}, item
        if "colors-hyprland" in item["path"]:
            assert "colors-hyprland.lua" in tree or "HYPR_LUA_PYWAL_LUA" in tree
            assert "error(" in BRIDGES.read_text()
        if "liquid-glass" in item["path"]:
            assert "liquid-glass" in BRIDGES.read_text()
            assert "source =" not in BRIDGES.read_text()
    assert "liquid-glass.conf" in BRIDGES.read_text()
    generated = payload["generated_not_sourced"]
    assert any(item["path"].endswith("monitors.conf") for item in generated)
    artifact = HYPR / "lua/generated/monitors.lua"
    assert artifact.is_file()
    assert "do not apply at startup" in artifact.read_text().lower() or "not sourced" in artifact.read_text().lower()
    for item in payload["runtime_bridges"]:
        assert item["lua_api"] == "explicit bridge"
        assert (ROOT / item["file"]).is_file()


def test_pywal_loader_errors_when_generated_lua_is_missing():
    body = BRIDGES.read_text()
    appearance = APPEARANCE.read_text()
    assert "local f = io.open" not in appearance
    assert "if not f then return" not in body
    assert "if f then" not in body
    assert "error(" in body
    assert "colors-hyprland.lua" in body
    assert "loadfile" in body


def test_sync_pywal_writes_generated_lua_artifact(tmp_path: Path):
    cache = tmp_path / ".cache/wal"
    cache.mkdir(parents=True)
    (cache / "colors.json").write_text(
        json.dumps(
            {
                "special": {"background": "#181f23", "foreground": "#d1deda"},
                "colors": {f"color{i}": f"#{i:02x}8c3e{(i * 17) % 256:02x}" for i in range(16)},
            }
        )
    )
    env = os.environ | {"HOME": str(tmp_path)}
    subprocess.run(["python3", str(SYNC_PYWAL)], check=True, env=env, cwd=ROOT)
    artifact = cache / "colors-hyprland.lua"
    conf = cache / "colors-hyprland.conf"
    assert artifact.is_file()
    assert conf.is_file()
    text = artifact.read_text()
    assert text.splitlines()[0].startswith("-- Generated by sync-pywal-theme.py")
    assert "hl.config" in text
    assert "active_border" in text
    assert "hyprglass_tint" in text or "tint_color" in text


def test_liquid_glass_bridge_is_explicit_and_fail_closed():
    body = BRIDGES.read_text()
    glass = (HYPR / "lua/generated/liquid_glass.lua").read_text()
    assert "Hermes" in glass
    assert "opacity" in glass
    assert "liquid-glass.conf" in body
    assert "liquid-glass.conf" in glass
    assert "error(" in body
    assert "source =" not in body
    assert "source =" not in glass
    fragment = ROOT / "config/hermes-liquid-glass/hypr/liquid-glass.conf"
    assert fragment.is_file()


def test_generated_monitors_artifact_does_not_edit_monitors_conf():
    before = MONITORS_CONF.read_bytes()
    digest = hashlib.sha256(before).hexdigest()
    assert before.startswith(b"# Generated from the live layout by persist-monitor-layout.py.")
    subprocess.run(["python3", str(GENERATOR)], check=True, cwd=ROOT)
    after = MONITORS_CONF.read_bytes()
    assert hashlib.sha256(after).hexdigest() == digest
    artifact = HYPR / "lua/generated/monitors.lua"
    text = artifact.read_text()
    assert "hl.monitor" in text or "output=" in text
    assert "DP-1" in text
    assert "do not hand-edit" in text.lower() or "not sourced" in text.lower()


def test_phone_display_and_gui_e2e_use_native_eval_with_lua_provider():
    phone = PHONE.read_text()
    e2e = GUI_E2E.read_text()
    apply = APPLY_PYWAL.read_text()
    for body in (phone, e2e):
        assert "configProvider: lua" in body
        assert "-r eval" in body
        assert "hl.monitor" in body
        assert "hl.workspace_rule" in body
        assert "jq -Rrn" in body
        assert "dispatch focusmonitor" not in body
    assert "hl.window_rule" in e2e
    assert "workspace ${workspace} silent" in e2e
    assert "keyword monitor" in phone and "keyword workspace" in phone
    assert "PHONE_DISPLAY_MODE:-3120x1440@120" in phone
    assert "keyword monitor" in e2e and "keyword workspace" in e2e
    assert "colors-hyprland.lua" in apply
    assert "hyprctl keyword" in apply


def test_legacy_startup_selection_is_unchanged():
    assert LIVE_LINK.is_symlink()
    assert LIVE_LINK.resolve() == HYPR / "hyprland.legacy.conf"
    assert "hyprctl reload" not in BRIDGES.read_text()
    assert "systemctl" not in BRIDGES.read_text()
