-- Generated from the audited bind directives in hyprland.legacy.conf.
hl.bind("SUPER + Return", hl.dsp.exec_raw("exec", "kitty"))
hl.bind("SUPER + SHIFT + E", hl.dsp.exec_raw("exec", "nautilus"))
hl.bind("SUPER + SHIFT + Q", hl.dsp.exec_raw("killactive", ""))
hl.bind("SUPER + N", hl.dsp.exec_raw("exec", "$HOME/workspace/.files/scripts/night-mode.sh off"), {locked=true})
hl.bind("SUPER + space", hl.dsp.exec_raw("exec", "qs -c noctalia-shell ipc --any-display call launcher toggle"))
hl.bind("SUPER + SHIFT + space", hl.dsp.exec_raw("exec", "rofi -show run"))
hl.bind("SUPER + Tab", hl.dsp.exec_raw("exec", "rofi -show window"))
hl.bind("SUPER + slash", hl.dsp.exec_raw("exec", "$HOME/workspace/.files/scripts/keybind-cheatsheet.py"))
hl.bind("SUPER + O", hl.dsp.exec_raw("exec", "$HOME/workspace/.files/scripts/workspace-atlas.py"))
hl.bind("SUPER + V", hl.dsp.exec_raw("exec", "cliphist list | rofi -dmenu | cliphist decode | wl-copy"))
hl.bind("SUPER + F", hl.dsp.exec_raw("fullscreen", "0"))
hl.bind("SUPER + SHIFT + F", hl.dsp.exec_raw("togglefloating", ""))
hl.bind("SUPER + SHIFT + F", hl.dsp.exec_raw("resizewindowpixel", "exact 960 540"))
hl.bind("SUPER + SHIFT + F", hl.dsp.exec_raw("centerwindow", ""))
hl.bind("SUPER + H", hl.dsp.exec_raw("movefocus", "l"))
hl.bind("SUPER + J", hl.dsp.exec_raw("movefocus", "d"))
hl.bind("SUPER + K", hl.dsp.exec_raw("movefocus", "u"))
hl.bind("SUPER + L", hl.dsp.exec_raw("movefocus", "r"))
hl.bind("SUPER + left", hl.dsp.exec_raw("movefocus", "l"))
hl.bind("SUPER + down", hl.dsp.exec_raw("movefocus", "d"))
hl.bind("SUPER + up", hl.dsp.exec_raw("movefocus", "u"))
hl.bind("SUPER + right", hl.dsp.exec_raw("movefocus", "r"))
hl.bind("SUPER + SHIFT + H", hl.dsp.exec_raw("movewindoworgroup", "l"))
hl.bind("SUPER + SHIFT + J", hl.dsp.exec_raw("movewindoworgroup", "d"))
hl.bind("SUPER + SHIFT + K", hl.dsp.exec_raw("movewindoworgroup", "u"))
hl.bind("SUPER + SHIFT + L", hl.dsp.exec_raw("movewindoworgroup", "r"))
hl.bind("SUPER + SHIFT + left", hl.dsp.exec_raw("movewindoworgroup", "l"))
hl.bind("SUPER + SHIFT + down", hl.dsp.exec_raw("movewindoworgroup", "d"))
hl.bind("SUPER + SHIFT + up", hl.dsp.exec_raw("movewindoworgroup", "u"))
hl.bind("SUPER + SHIFT + right", hl.dsp.exec_raw("movewindoworgroup", "r"))
hl.bind("SUPER + C", hl.dsp.exec_raw("layoutmsg", "preselect l"))
hl.bind("SUPER + V", hl.dsp.exec_raw("layoutmsg", "preselect d"))
hl.bind("SUPER + W", hl.dsp.exec_raw("togglegroup", ""))
hl.bind("SUPER + G", hl.dsp.exec_raw("exec", "$HOME/workspace/.files/scripts/hypr-group-workspace.sh"))
hl.bind("SUPER + E", hl.dsp.exec_raw("layoutmsg", "togglesplit"))
hl.bind("SUPER + bracketright", hl.dsp.exec_raw("changegroupactive", "f"))
hl.bind("SUPER + bracketleft", hl.dsp.exec_raw("changegroupactive", "b"))
hl.bind("SUPER + SHIFT + G", hl.dsp.exec_raw("moveoutofgroup", ""))
hl.bind("SUPER + A", hl.dsp.exec_raw("focuscurrentorlast", ""))
hl.bind("SUPER + 1", hl.dsp.exec_raw("workspace", "1"))
hl.bind("SUPER + 2", hl.dsp.exec_raw("workspace", "2"))
hl.bind("SUPER + 3", hl.dsp.exec_raw("workspace", "3"))
hl.bind("SUPER + 4", hl.dsp.exec_raw("workspace", "4"))
hl.bind("SUPER + 5", hl.dsp.exec_raw("workspace", "5"))
hl.bind("SUPER + 6", hl.dsp.exec_raw("workspace", "6"))
hl.bind("SUPER + 7", hl.dsp.exec_raw("workspace", "7"))
hl.bind("SUPER + 8", hl.dsp.exec_raw("workspace", "8"))
hl.bind("SUPER + 9", hl.dsp.exec_raw("workspace", "9"))
hl.bind("SUPER + 0", hl.dsp.exec_raw("workspace", "10"))
hl.bind("SUPER + SHIFT + 1", hl.dsp.exec_raw("movetoworkspace", "1"))
hl.bind("SUPER + SHIFT + 2", hl.dsp.exec_raw("movetoworkspace", "2"))
hl.bind("SUPER + SHIFT + 3", hl.dsp.exec_raw("movetoworkspace", "3"))
hl.bind("SUPER + SHIFT + 4", hl.dsp.exec_raw("movetoworkspace", "4"))
hl.bind("SUPER + SHIFT + 5", hl.dsp.exec_raw("movetoworkspace", "5"))
hl.bind("SUPER + SHIFT + 6", hl.dsp.exec_raw("movetoworkspace", "6"))
hl.bind("SUPER + SHIFT + 7", hl.dsp.exec_raw("movetoworkspace", "7"))
hl.bind("SUPER + SHIFT + 8", hl.dsp.exec_raw("movetoworkspace", "8"))
hl.bind("SUPER + SHIFT + 9", hl.dsp.exec_raw("movetoworkspace", "9"))
hl.bind("SUPER + SHIFT + 0", hl.dsp.exec_raw("movetoworkspace", "10"))
hl.bind("SUPER + SHIFT + CTRL + H", hl.dsp.exec_raw("movecurrentworkspacetomonitor", "l"))
hl.bind("SUPER + SHIFT + CTRL + L", hl.dsp.exec_raw("movecurrentworkspacetomonitor", "r"))
hl.bind("SUPER + SHIFT + CTRL + K", hl.dsp.exec_raw("movecurrentworkspacetomonitor", "u"))
hl.bind("SUPER + SHIFT + CTRL + J", hl.dsp.exec_raw("movecurrentworkspacetomonitor", "d"))
hl.bind("SUPER + SHIFT + minus", hl.dsp.exec_raw("movetoworkspacesilent", "special"))
hl.bind("SUPER + minus", hl.dsp.exec_raw("togglespecialworkspace", ""))
hl.bind("SUPER + grave", hl.dsp.exec_raw("togglespecialworkspace", "scratch_term"))
hl.bind("SUPER + CTRL + equal", hl.dsp.exec_raw("exec", "$HOME/workspace/.files/scripts/hypr-gaps.sh increase"))
hl.bind("SUPER + CTRL + minus", hl.dsp.exec_raw("exec", "$HOME/workspace/.files/scripts/hypr-gaps.sh decrease"))
hl.bind("SUPER + CTRL + 0", hl.dsp.exec_raw("exec", "$HOME/workspace/.files/scripts/hypr-gaps.sh reset"))
hl.bind("SUPER + SHIFT + R", hl.dsp.exec_raw("exec", "$HOME/workspace/.files/scripts/reload-desktop.sh"))
hl.bind("SUPER + SHIFT + T", hl.dsp.exec_raw("exec", "$HOME/workspace/.files/scripts/desktop-wallpaper-picker.sh"))
hl.bind("SUPER + SHIFT + comma", hl.dsp.exec_raw("exec", "$HOME/workspace/.files/scripts/desktop-wallpaper-step.py previous"))
hl.bind("SUPER + SHIFT + period", hl.dsp.exec_raw("exec", "$HOME/workspace/.files/scripts/desktop-wallpaper-step.py next"))
hl.bind("SUPER + CTRL + W", hl.dsp.exec_raw("exec", "$HOME/workspace/.files/scripts/wallpaper-mode.sh cycle"))
hl.bind("SUPER + ALT + W", hl.dsp.exec_raw("exec", "$HOME/workspace/.files/scripts/wallpaper-mode.sh toggle"))
hl.bind("SUPER + CTRL + B", hl.dsp.exec_raw("exec", "$HOME/workspace/.files/scripts/bar-mode.sh toggle"))
hl.bind("SUPER + ALT + P", hl.dsp.exec_raw("exec", "$HOME/workspace/.files/scripts/phone-display.sh toggle"))
hl.bind("SUPER + SHIFT + B", hl.dsp.exec_raw("submap", "wallpaper · a auto │ s span │ f fill │ i fit │ c center │ t tile │ x stretch"))
hl.bind("SUPER + P", hl.dsp.exec_raw("exec", "grim -g \"$(slurp)\" ~/Pictures/screenshots/screenshot-$(date +%Y%m%d-%H%M%S).png"))
hl.bind("SUPER + SHIFT + P", hl.dsp.exec_raw("exec", "grim -g \"$(slurp)\" - | wl-copy"))
hl.bind("SUPER + CTRL + P", hl.dsp.exec_raw("exec", "grim ~/Pictures/screenshots/screenshot-$(date +%Y%m%d-%H%M%S).png"))
hl.bind("SUPER + CTRL + SHIFT + P", hl.dsp.exec_raw("exec", "grim - | wl-copy"))
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_raw("exec", "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), {locked=true,repeating=true})
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_raw("exec", "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), {locked=true,repeating=true})
hl.bind("XF86AudioMute", hl.dsp.exec_raw("exec", "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), {locked=true})
hl.bind("XF86AudioPlay", hl.dsp.exec_raw("exec", "playerctl play-pause"), {locked=true})
hl.bind("XF86AudioPause", hl.dsp.exec_raw("exec", "playerctl play-pause"), {locked=true})
hl.bind("XF86AudioNext", hl.dsp.exec_raw("exec", "playerctl next"), {locked=true})
hl.bind("XF86AudioPrev", hl.dsp.exec_raw("exec", "playerctl previous"), {locked=true})
hl.bind("ALT + 1", hl.dsp.exec_raw("exec", "$HOME/.local/bin/audio-evolve select 1 --notify"))
hl.bind("ALT + 2", hl.dsp.exec_raw("exec", "$HOME/.local/bin/audio-evolve select 2 --notify"))
hl.bind("ALT + 3", hl.dsp.exec_raw("exec", "$HOME/.local/bin/audio-evolve select 3 --notify"))
hl.bind("ALT + 4", hl.dsp.exec_raw("exec", "$HOME/.local/bin/audio-evolve select 4 --notify"))
hl.bind("ALT + 5", hl.dsp.exec_raw("exec", "$HOME/.local/bin/audio-evolve select 5 --notify"))
hl.bind("ALT + 6", hl.dsp.exec_raw("exec", "$HOME/.local/bin/audio-evolve select 6 --notify"))
hl.bind("ALT + 7", hl.dsp.exec_raw("exec", "$HOME/.local/bin/audio-evolve select 7 --notify"))
hl.bind("ALT + 8", hl.dsp.exec_raw("exec", "$HOME/.local/bin/audio-evolve select 8 --notify"))
hl.bind("ALT + 9", hl.dsp.exec_raw("exec", "$HOME/.local/bin/audio-evolve select 9 --notify"))
hl.bind("ALT + 0", hl.dsp.exec_raw("exec", "$HOME/.local/bin/audio-evolve select 0 --notify"))
hl.bind("ALT + F12", hl.dsp.exec_raw("exec", "$HOME/.local/bin/audio-sink bitperfect"))
hl.bind("ALT + F11", hl.dsp.exec_raw("exec", "$HOME/.local/bin/audio-sink bs2b"))
hl.bind("ALT + F10", hl.dsp.exec_raw("exec", "$HOME/.local/bin/audio-sink room"))
hl.bind("ALT + F9", hl.dsp.exec_raw("exec", "$HOME/.local/bin/audio-sink aural"))
hl.bind("SUPER + SHIFT + A", hl.dsp.exec_raw("exec", "notify-send -u critical -t 5000 \"Audio restart in 3 seconds\" \"PipeWire will briefly interrupt active streams\" && sleep 3 && systemctl --user restart pipewire pipewire-pulse && notify-send \"PipeWire\" \"Audio stack restarted\""))
hl.bind("SUPER + S", hl.dsp.exec_raw("exec", "$HOME/workspace/.files/scripts/speak-selection.sh"))
hl.bind("SUPER + R", hl.dsp.exec_raw("submap", "resize"))
hl.bind("SUPER + SHIFT + X", hl.dsp.exec_raw("submap", "system · l lock │ n night │ s suspend │ S shutdown │ r reboot │ e exit"))
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), {mouse=true})
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), {mouse=true})
hl.define_submap("wallpaper · a auto │ s span │ f fill │ i fit │ c center │ t tile │ x stretch", "reset", function()
  hl.bind("A", hl.dsp.exec_raw("exec", "$HOME/workspace/.files/scripts/wallpaper-mode.sh draw auto"))
  hl.bind("A", hl.dsp.exec_raw("submap", "reset"))
  hl.bind("S", hl.dsp.exec_raw("exec", "$HOME/workspace/.files/scripts/wallpaper-mode.sh draw span"))
  hl.bind("S", hl.dsp.exec_raw("submap", "reset"))
  hl.bind("F", hl.dsp.exec_raw("exec", "$HOME/workspace/.files/scripts/wallpaper-mode.sh draw fill"))
  hl.bind("F", hl.dsp.exec_raw("submap", "reset"))
  hl.bind("I", hl.dsp.exec_raw("exec", "$HOME/workspace/.files/scripts/wallpaper-mode.sh draw fit"))
  hl.bind("I", hl.dsp.exec_raw("submap", "reset"))
  hl.bind("C", hl.dsp.exec_raw("exec", "$HOME/workspace/.files/scripts/wallpaper-mode.sh draw center"))
  hl.bind("C", hl.dsp.exec_raw("submap", "reset"))
  hl.bind("T", hl.dsp.exec_raw("exec", "$HOME/workspace/.files/scripts/wallpaper-mode.sh draw tile"))
  hl.bind("T", hl.dsp.exec_raw("submap", "reset"))
  hl.bind("X", hl.dsp.exec_raw("exec", "$HOME/workspace/.files/scripts/wallpaper-mode.sh draw stretch"))
  hl.bind("X", hl.dsp.exec_raw("submap", "reset"))
  hl.bind("Return", hl.dsp.exec_raw("submap", "reset"))
  hl.bind("escape", hl.dsp.exec_raw("submap", "reset"))
end)
hl.define_submap("resize", "reset", function()
  hl.bind("H", hl.dsp.exec_raw("resizeactive", "-40 0"), {repeating=true})
  hl.bind("J", hl.dsp.exec_raw("resizeactive", "0 40"), {repeating=true})
  hl.bind("K", hl.dsp.exec_raw("resizeactive", "0 -40"), {repeating=true})
  hl.bind("L", hl.dsp.exec_raw("resizeactive", "40 0"), {repeating=true})
  hl.bind("left", hl.dsp.exec_raw("resizeactive", "-40 0"), {repeating=true})
  hl.bind("down", hl.dsp.exec_raw("resizeactive", "0 40"), {repeating=true})
  hl.bind("up", hl.dsp.exec_raw("resizeactive", "0 -40"), {repeating=true})
  hl.bind("right", hl.dsp.exec_raw("resizeactive", "40 0"), {repeating=true})
  hl.bind("Return", hl.dsp.exec_raw("submap", "reset"))
  hl.bind("escape", hl.dsp.exec_raw("submap", "reset"))
end)
hl.define_submap("system · l lock │ n night │ s suspend │ S shutdown │ r reboot │ e exit", "reset", function()
  hl.bind("L", hl.dsp.exec_raw("exec", "hyprlock"))
  hl.bind("L", hl.dsp.exec_raw("submap", "reset"))
  hl.bind("N", hl.dsp.exec_raw("exec", "$HOME/workspace/.files/scripts/night-mode.sh on"))
  hl.bind("N", hl.dsp.exec_raw("submap", "reset"))
  hl.bind("E", hl.dsp.exec_raw("exit", ""))
  hl.bind("S", hl.dsp.exec_raw("exec", "systemctl suspend"))
  hl.bind("S", hl.dsp.exec_raw("submap", "reset"))
  hl.bind("R", hl.dsp.exec_raw("exec", "systemctl reboot"))
  hl.bind("SHIFT + S", hl.dsp.exec_raw("exec", "systemctl poweroff"))
  hl.bind("Return", hl.dsp.exec_raw("submap", "reset"))
  hl.bind("escape", hl.dsp.exec_raw("submap", "reset"))
end)
