#!/bin/bash
# 5-configure-system.sh - Apply system optimizations for AI agent workloads
# Based on: repos/migrate/research/system-optimization.md
#
# Optimizes CachyOS for 100-1000+ concurrent AI agents
# Run after: 4-install-packages-cachyos.sh

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
LOG_DIR="$SCRIPT_DIR/../logs"
DATE=$(date +%Y%m%d-%H%M%S)
LOG_FILE="$LOG_DIR/configure-system-$DATE.log"
BACKUP_DIR="$LOG_DIR/config-backup-$DATE"

mkdir -p "$LOG_DIR" "$BACKUP_DIR"

log() { echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $*" | tee -a "$LOG_FILE"; }
log_warn() { echo -e "${YELLOW}[$(date +'%Y-%m-%d %H:%M:%S')] WARNING:${NC} $*" | tee -a "$LOG_FILE"; }
log_error() { echo -e "${RED}[$(date +'%Y-%m-%d %H:%M:%S')] ERROR:${NC} $*" | tee -a "$LOG_FILE"; }
log_section() { echo -e "\n${BLUE}========== $* ==========${NC}\n" | tee -a "$LOG_FILE"; }

error_exit() {
    log_error "$1"
    exit 1
}

# Check root
if [[ $EUID -ne 0 ]]; then
   error_exit "This script must be run as root (use sudo)"
fi

# Backup existing config
backup_file() {
    local file="$1"
    if [[ -f "$file" ]]; then
        cp -a "$file" "$BACKUP_DIR/$(basename $file).backup"
        log "Backed up: $file"
    fi
}

# ===================================
# KERNEL PARAMETERS (sysctl)
# ===================================

configure_sysctl() {
    log_section "Configuring Kernel Parameters (sysctl)"

    backup_file "/etc/sysctl.conf"
    backup_file "/etc/sysctl.d/99-ai-workload.conf"

    log "Writing optimized sysctl configuration..."

    cat > /etc/sysctl.d/99-ai-workload.conf << 'EOF'
# AI Agent Workload Optimization
# Generated by migration scripts
# Optimized for 1000+ concurrent AI agents

# ===== FILE SYSTEM =====
# Massively increase file descriptor limits
fs.file-max = 2097152
fs.nr_open = 2097152

# Increase inotify limits for file watching
fs.inotify.max_user_watches = 524288
fs.inotify.max_user_instances = 512
fs.inotify.max_queued_events = 32768

# AIO (Async I/O) limits
fs.aio-max-nr = 1048576

# ===== MEMORY MANAGEMENT =====
# Reduce swap usage (we have enough RAM)
vm.swappiness = 10

# Increase cache pressure to free memory faster
vm.vfs_cache_pressure = 50

# Allow more dirty pages for better write performance
vm.dirty_ratio = 40
vm.dirty_background_ratio = 10

# Increase writeback interval for better batching
vm.dirty_writeback_centisecs = 500
vm.dirty_expire_centisecs = 3000

# Transparent Huge Pages - enable for performance
vm.nr_hugepages = 128

# ===== NETWORK STACK =====
# Increase network buffer sizes
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.core.rmem_default = 16777216
net.core.wmem_default = 16777216

# TCP buffer tuning
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.tcp_mem = 67108864 67108864 67108864

# Increase connection limits
net.core.somaxconn = 65535
net.core.netdev_max_backlog = 65536
net.ipv4.tcp_max_syn_backlog = 8192

# Enable TCP fast open
net.ipv4.tcp_fastopen = 3

# TCP keepalive tuning
net.ipv4.tcp_keepalive_time = 600
net.ipv4.tcp_keepalive_probes = 5
net.ipv4.tcp_keepalive_intvl = 15

# Increase local port range
net.ipv4.ip_local_port_range = 1024 65535

# Enable TCP window scaling
net.ipv4.tcp_window_scaling = 1

# ===== PROCESS LIMITS =====
# Increase PID limit
kernel.pid_max = 4194304

# Increase thread limits
kernel.threads-max = 4194304

# ===== SEMAPHORES & SHARED MEMORY =====
# Increase IPC limits for database/cache systems
kernel.sem = 250 32000 100 1024
kernel.shmmax = 68719476736
kernel.shmall = 4294967296
kernel.shmmni = 8192

# ===== PERFORMANCE =====
# Disable unnecessary kernel features
kernel.nmi_watchdog = 0

# Reduce kernel log verbosity
kernel.printk = 3 4 1 3

EOF

    log "Applying sysctl configuration..."
    sysctl -p /etc/sysctl.d/99-ai-workload.conf || log_warn "Some sysctl parameters may have failed"

    log "Kernel parameters configured"
}

# ===================================
# SYSTEMD LIMITS
# ===================================

configure_systemd_limits() {
    log_section "Configuring systemd Limits"

    backup_file "/etc/systemd/system.conf"
    backup_file "/etc/systemd/user.conf"

    log "Configuring system-wide limits..."

    # System limits
    cat >> /etc/systemd/system.conf << 'EOF'

# AI Workload Optimizations
DefaultLimitNOFILE=1048576
DefaultLimitNPROC=unlimited
DefaultTasksMax=infinity
DefaultLimitMEMLOCK=infinity
EOF

    # User limits
    cat >> /etc/systemd/user.conf << 'EOF'

# AI Workload Optimizations
DefaultLimitNOFILE=1048576
DefaultLimitNPROC=unlimited
DefaultTasksMax=infinity
EOF

    log "Reloading systemd configuration..."
    systemctl daemon-reexec || log_warn "systemd reload may require reboot"

    log "systemd limits configured"
}

# ===================================
# PAM LIMITS
# ===================================

configure_pam_limits() {
    log_section "Configuring PAM Limits"

    backup_file "/etc/security/limits.conf"

    log "Writing PAM limits configuration..."

    cat >> /etc/security/limits.conf << 'EOF'

# AI Agent Workload Limits
# Allow all users to create many processes and open many files

*    soft    nofile    1048576
*    hard    nofile    1048576
*    soft    nproc     unlimited
*    hard    nproc     unlimited
*    soft    memlock   unlimited
*    hard    memlock   unlimited
*    soft    stack     unlimited
*    hard    stack     unlimited

# Root limits
root soft    nofile    1048576
root hard    nofile    1048576
root soft    nproc     unlimited
root hard    nproc     unlimited
EOF

    log "PAM limits configured"
}

# ===================================
# I/O SCHEDULER OPTIMIZATION
# ===================================

configure_io_scheduler() {
    log_section "Configuring I/O Schedulers"

    log "Detecting storage devices..."

    # NVMe devices - use 'none' scheduler
    for nvme in /sys/block/nvme*; do
        if [[ -d "$nvme" ]]; then
            local device=$(basename "$nvme")
            log "Setting scheduler for NVMe: $device → none"
            echo "none" > "/sys/block/$device/queue/scheduler" 2>/dev/null || log_warn "Failed to set scheduler for $device"
        fi
    done

    # SATA SSDs - use 'mq-deadline' or 'none'
    for sd in /sys/block/sd*; do
        if [[ -d "$sd" ]]; then
            local device=$(basename "$sd")
            # Check if it's an SSD
            local rotational=$(cat "/sys/block/$device/queue/rotational" 2>/dev/null || echo "1")
            if [[ "$rotational" == "0" ]]; then
                log "Setting scheduler for SSD: $device → mq-deadline"
                echo "mq-deadline" > "/sys/block/$device/queue/scheduler" 2>/dev/null || log_warn "Failed to set scheduler for $device"
            fi
        fi
    done

    # Make permanent via udev rule
    log "Creating udev rule for persistent I/O scheduler..."

    cat > /etc/udev/rules.d/60-io-scheduler.rules << 'EOF'
# I/O Scheduler optimization for AI workloads
# NVMe devices: none (bypass scheduling)
ACTION=="add|change", KERNEL=="nvme[0-9]n[0-9]", ATTR{queue/scheduler}="none"

# SATA SSDs: mq-deadline (optimized for SSDs)
ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="mq-deadline"
EOF

    udevadm control --reload-rules

    log "I/O schedulers configured"
}

# ===================================
# MOUNT OPTIONS OPTIMIZATION
# ===================================

configure_mount_options() {
    log_section "Verifying Mount Options"

    backup_file "/etc/fstab"

    log "Current mount options (from /etc/fstab):"
    grep -v '^#' /etc/fstab | grep -v '^$' | tee -a "$LOG_FILE"

    log ""
    log_warn "Mount options should have been configured during disk partitioning"
    log "Recommended mount options (from partition-design.md):"
    log "  - XFS workspace: noatime,nodiratime,logbufs=8,logbsize=256k,largeio,swalloc,allocsize=256k"
    log "  - ext4 root/home: noatime,nodiratime,data=writeback,barrier=0"
    log "  - Btrfs: noatime,compress=zstd:1,space_cache=v2"

    log ""
    read -p "Review fstab and press Enter to continue (or Ctrl+C to abort for manual editing)..."
}

# ===================================
# GRUB/BOOTLOADER OPTIMIZATION
# ===================================

configure_bootloader() {
    log_section "Configuring Bootloader (systemd-boot)"

    if [[ ! -d /boot/efi/loader ]]; then
        log_warn "systemd-boot not detected, skipping bootloader configuration"
        return 0
    fi

    backup_file "/boot/efi/loader/entries/cachyos.conf"

    log "Checking for CachyOS boot entry..."

    local entry_file=""
    for entry in /boot/efi/loader/entries/*.conf; do
        if grep -q "CachyOS\|cachyos" "$entry" 2>/dev/null; then
            entry_file="$entry"
            break
        fi
    done

    if [[ -z "$entry_file" ]]; then
        log_warn "No CachyOS boot entry found in /boot/efi/loader/entries/"
        log "Boot entries found:"
        ls -1 /boot/efi/loader/entries/ | tee -a "$LOG_FILE"
        return 0
    fi

    log "Found boot entry: $entry_file"

    # Check current kernel parameters
    log "Current kernel parameters:"
    grep "^options" "$entry_file" | tee -a "$LOG_FILE"

    log ""
    log "Recommended kernel parameters for AI workload:"
    log "  mitigations=off - Disable CPU vulnerability mitigations for performance"
    log "  transparent_hugepage=always - Enable THP"
    log "  elevator=none - Force I/O scheduler"
    log "  intel_pstate=performance (Intel) or amd_pstate=active (AMD)"
    log ""
    log_warn "Kernel parameter changes require manual editing of: $entry_file"
    log_warn "Then run: bootctl update"
}

# ===================================
# CPU GOVERNOR
# ===================================

configure_cpu_governor() {
    log_section "Configuring CPU Governor"

    if [[ ! -d /sys/devices/system/cpu/cpu0/cpufreq ]]; then
        log_warn "CPU frequency scaling not available"
        return 0
    fi

    log "Setting CPU governor to 'performance'..."

    for cpu in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
        echo "performance" > "$cpu" 2>/dev/null || log_warn "Failed to set governor for $cpu"
    done

    # Make persistent
    log "Installing cpupower for persistent governor..."
    pacman -S --needed --noconfirm cpupower || log_warn "Failed to install cpupower"

    if command -v cpupower &> /dev/null; then
        cpupower frequency-set -g performance || log_warn "cpupower failed"

        log "Enabling cpupower service..."
        systemctl enable cpupower.service || log_warn "Failed to enable cpupower service"
    fi

    log "CPU governor set to performance"
}

# ===================================
# VERIFICATION
# ===================================

verify_configuration() {
    log_section "Verification"

    log "Checking applied settings..."

    echo "File descriptor limits:" | tee -a "$LOG_FILE"
    echo "  fs.file-max: $(sysctl -n fs.file-max)"
    echo "  fs.nr_open: $(sysctl -n fs.nr_open)"

    echo "" | tee -a "$LOG_FILE"
    echo "Memory settings:" | tee -a "$LOG_FILE"
    echo "  vm.swappiness: $(sysctl -n vm.swappiness)"
    echo "  vm.dirty_ratio: $(sysctl -n vm.dirty_ratio)"

    echo "" | tee -a "$LOG_FILE"
    echo "Network settings:" | tee -a "$LOG_FILE"
    echo "  net.core.somaxconn: $(sysctl -n net.core.somaxconn)"
    echo "  net.ipv4.ip_local_port_range: $(sysctl -n net.ipv4.ip_local_port_range)"

    echo "" | tee -a "$LOG_FILE"
    echo "I/O Schedulers:" | tee -a "$LOG_FILE"
    for dev in /sys/block/{nvme*,sd*}; do
        if [[ -d "$dev" ]]; then
            local device=$(basename "$dev")
            local scheduler=$(cat "$dev/queue/scheduler" 2>/dev/null || echo "N/A")
            echo "  $device: $scheduler"
        fi
    done

    echo "" | tee -a "$LOG_FILE"
    echo "CPU Governor:" | tee -a "$LOG_FILE"
    if [[ -f /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor ]]; then
        echo "  $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)"
    else
        echo "  N/A"
    fi
}

# ===================================
# SUMMARY
# ===================================

generate_summary() {
    log_section "Configuration Summary"

    cat << EOF

${GREEN}✅ SYSTEM CONFIGURATION COMPLETED${NC}

📁 Backups saved to: $BACKUP_DIR
📝 Log file: $LOG_FILE

Applied Optimizations:
  ✅ Kernel parameters (sysctl) - File descriptors: 2M, Network tuning, Memory optimization
  ✅ systemd limits - Unlimited processes, 1M file descriptors
  ✅ PAM limits - Unlimited resources for all users
  ✅ I/O Schedulers - 'none' for NVMe, 'mq-deadline' for SSDs
  ✅ CPU Governor - Set to 'performance'

⚠️  Manual Steps Required:
1. Review and optimize kernel parameters in systemd-boot entry
2. Reboot to apply all changes:
   sudo reboot

After Reboot:
3. Verify settings with: ulimit -a
4. Check file descriptor limit: ulimit -n (should be 1048576)
5. Verify I/O schedulers: cat /sys/block/*/queue/scheduler
6. Run restoration script: 6-restore-configs.sh

Performance Notes:
- System optimized for 1000+ concurrent AI agents
- File descriptors: 2M (vs default 1024)
- Network connections: 65K max
- Swappiness: 10 (minimal swap usage)
- I/O: Optimized for parallel workloads

EOF
}

# ===================================
# MAIN EXECUTION
# ===================================

main() {
    log "Starting system configuration..."
    log "Backup directory: $BACKUP_DIR"
    log "Log file: $LOG_FILE"

    configure_sysctl
    configure_systemd_limits
    configure_pam_limits
    configure_io_scheduler
    configure_mount_options
    configure_bootloader
    configure_cpu_governor

    verify_configuration
    generate_summary

    log ""
    log "${GREEN}✅ Configuration completed successfully!${NC}"
    log "📁 Backups: $BACKUP_DIR"
    log "📝 Log: $LOG_FILE"
    log ""
    log "${YELLOW}⚠️  REBOOT REQUIRED to apply all changes${NC}"
    log "After reboot, run: 6-restore-configs.sh"
}

main
