#!/usr/bin/env python3
"""Synchronize pywal colors into terminal-native formats with safe contrast."""

from __future__ import annotations

import json
from pathlib import Path

CACHE = Path.home() / ".cache/wal"
COLORS_JSON = CACHE / "colors.json"
ALACRITTY = CACHE / "colors-alacritty.toml"
KITTY = CACHE / "colors-kitty.conf"
WAYBAR = CACHE / "colors-waybar.css"
WAYBAR_SEMANTIC = CACHE / "colors-waybar-semantic.css"
HYPRLAND = CACHE / "colors-hyprland.conf"
TMUX = CACHE / "colors-tmux.conf"
DUNST_SOURCE = Path(__file__).resolve().parents[1] / "config/dunst/dunstrc"
DUNST = CACHE / "dunstrc"
MIN_MUTED_CONTRAST = 5.0


def rgb(value: str) -> tuple[int, int, int]:
    value = value.strip().lstrip("#")
    return tuple(int(value[index : index + 2], 16) for index in (0, 2, 4))


def hex_color(value: tuple[int, int, int]) -> str:
    return "#" + "".join(f"{channel:02x}" for channel in value)


def luminance(value: str) -> float:
    channels = []
    for channel in rgb(value):
        normalized = channel / 255
        channels.append(
            normalized / 12.92
            if normalized <= 0.04045
            else ((normalized + 0.055) / 1.055) ** 2.4
        )
    return 0.2126 * channels[0] + 0.7152 * channels[1] + 0.0722 * channels[2]


def contrast(first: str, second: str) -> float:
    light, dark = sorted((luminance(first), luminance(second)), reverse=True)
    return (light + 0.05) / (dark + 0.05)


def readable_muted(candidate: str, background: str) -> str:
    if contrast(candidate, background) >= MIN_MUTED_CONTRAST:
        return candidate
    target = (255, 255, 255) if luminance(background) < 0.35 else (0, 0, 0)
    source = rgb(candidate)
    for step in range(1, 21):
        ratio = step / 20
        adjusted = tuple(
            round(channel + (destination - channel) * ratio)
            for channel, destination in zip(source, target)
        )
        value = hex_color(adjusted)
        if contrast(value, background) >= MIN_MUTED_CONTRAST:
            return value
    return hex_color(target)


def replace_color(path: Path, prefix: str, value: str) -> None:
    if not path.exists():
        return
    lines = path.read_text().splitlines()
    replacement = f"{prefix}{value}"
    for index, line in enumerate(lines):
        if line.startswith(prefix):
            lines[index] = replacement
            break
    path.write_text("\n".join(lines) + "\n")


def main() -> None:
    palette = json.loads(COLORS_JSON.read_text())
    special = palette["special"]
    colors = palette["colors"]
    background = special["background"]
    foreground = special["foreground"]
    muted = readable_muted(colors["color8"], background)
    colors["color8"] = muted

    ALACRITTY.write_text(
        "\n".join(
            [
                "# Generated by sync-pywal-theme.py; do not edit.",
                "[colors]",
                "draw_bold_text_with_bright_colors = true",
                "",
                "[colors.primary]",
                f'background = "{background}"',
                f'foreground = "{foreground}"',
                f'dim_foreground = "{muted}"',
                "",
                "[colors.normal]",
                *[
                    f'{name} = "{colors[f"color{index}"]}"'
                    for index, name in enumerate(
                        ("black", "red", "green", "yellow", "blue", "magenta", "cyan", "white")
                    )
                ],
                "",
                "[colors.bright]",
                *[
                    f'{name} = "{colors[f"color{index}"]}"'
                    for index, name in zip(
                        range(8, 16),
                        ("black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"),
                    )
                ],
                "",
            ]
        )
    )
    replace_color(KITTY, "color8       ", muted)
    replace_color(WAYBAR, "@define-color color8 ", f"{muted};")
    semantic = {
        # Six readable stops are assigned across Waybar from left to right.
        **{
            f"wb_grad{index}": readable_muted(colors[f"color{index}"], background)
            for index in range(1, 7)
        },
        "wb_info": foreground,
        "wb_muted": muted,
        # Alerts stay semantically recognizable across arbitrary wallpapers.
        "wb_ok": readable_muted("#64d8a1", background),
        "wb_warning": readable_muted("#f0b65b", background),
        "wb_critical": readable_muted("#ff7085", background),
    }
    WAYBAR_SEMANTIC.write_text(
        "\n".join(
            [
                "/* Generated by sync-pywal-theme.py; do not edit. */",
                f"@define-color wb_background {background};",
                f"@define-color wb_foreground {foreground};",
                *[
                    f"@define-color {name} {value};"
                    for name, value in semantic.items()
                ],
                "",
            ]
        )
    )
    hypr = lambda value, alpha="ff": f"rgba({value.lstrip('#')}{alpha})"
    # color0/7 are background/foreground and 8–15 mirror 0–7 in pywal.
    # Using color1–6 therefore covers the complete chromatic palette once.
    active = [colors[f"color{index}"] for index in range(1, 7)]
    active_gradient = " ".join(hypr(value) for value in active) + " 90deg"
    tab_background = f"{hypr(background, 'b8')} {hypr(colors['color4'], '78')} 90deg"
    HYPRLAND.write_text(
        "\n".join(
            [
                "# Generated by sync-pywal-theme.py; do not edit.",
                f"general:col.active_border = {active_gradient}",
                f"general:col.inactive_border = {hypr(muted, '66')}",
                f"group:col.border_active = {active_gradient}",
                f"group:col.border_inactive = {hypr(muted, '66')}",
                f"group:col.border_locked_active = {active_gradient}",
                f"group:col.border_locked_inactive = {hypr(muted, '55')}",
                f"group:groupbar:col.active = {tab_background}",
                f"group:groupbar:col.inactive = {hypr(background, 'a8')}",
                f"group:groupbar:col.locked_active = {tab_background}",
                f"group:groupbar:col.locked_inactive = {hypr(background, '98')}",
                f"plugin:hyprglass:tint_color = 0x{background.lstrip('#')}38",
                f"group:groupbar:text_color = {hypr(foreground)}",
                f"group:groupbar:text_color_inactive = {hypr(foreground, 'e6')}",
                f"group:groupbar:text_color_locked_active = {hypr(foreground)}",
                f"group:groupbar:text_color_locked_inactive = {hypr(foreground, 'e6')}",
                "",
            ]
        )
    )
    tmux_active = readable_muted(colors["color4"], background)
    tmux_accent = readable_muted(colors["color6"], background)
    TMUX.write_text(
        "\n".join(
            [
                "# Generated by sync-pywal-theme.py; do not edit.",
                f"set -g status-style 'fg={foreground},bg=default'",
                f"set -g status-left '#[fg={tmux_active},bg=default,bold]❨ 󰆍 #S ❩ '",
                f"set -g status-right '#{{?client_prefix,#[fg={colors['color3']}]󰘳 PREFIX  ,}}#[fg={muted}]#{{b:pane_current_path}} #[fg={tmux_accent}]· #{{pane_current_command}} #[fg={muted}]· %H:%M '",
                f"setw -g window-status-style 'fg={muted},bg=default'",
                f"setw -g window-status-current-format '#[fg={tmux_active},bg=default,bold]❨ #I:#W#{{?window_zoomed_flag, 󰊓,}} ❩'",
                f"setw -g window-status-activity-style 'fg={colors['color3']},bg=default,bold'",
                f"setw -g window-status-bell-style 'fg={colors['color1']},bg=default,bold'",
                f"set -g pane-border-style 'fg={muted}'",
                f"set -g pane-active-border-style 'fg={tmux_active}'",
                f"set -g mode-style 'fg={background},bg={tmux_active},bold'",
                f"set -g message-style 'fg={foreground},bg={background}'",
                f"set -g message-command-style 'fg={tmux_accent},bg={background}'",
                f"set -g menu-style 'fg={foreground},bg={background}'",
                f"set -g menu-selected-style 'fg={background},bg={tmux_active},bold'",
                f"set -g menu-border-style 'fg={muted}'",
                f"set -g popup-style 'fg={foreground},bg={background}'",
                f"set -g popup-border-style 'fg={tmux_active}'",
                "",
            ]
        )
    )
    dunst_lines = DUNST_SOURCE.read_text().splitlines()
    section = ""
    for index, line in enumerate(dunst_lines):
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            section = stripped[1:-1]
            continue
        key = stripped.split("=", 1)[0].strip() if "=" in stripped else ""
        if section == "global" and key == "frame_color":
            dunst_lines[index] = f'    frame_color = "{tmux_active}"'
        elif section in {"urgency_low", "urgency_normal", "urgency_critical"}:
            if key == "background":
                alpha = {"urgency_low": "d9", "urgency_normal": "e0", "urgency_critical": "e8"}[section]
                dunst_lines[index] = f'    background = "{background}{alpha}"'
            elif key == "foreground":
                value = muted if section == "urgency_low" else foreground
                dunst_lines[index] = f'    foreground = "{value}"'
            elif key == "frame_color":
                dunst_lines[index] = f'    frame_color = "{semantic["wb_critical"]}"'
    DUNST.write_text("\n".join(dunst_lines) + "\n")
    print(
        json.dumps(
            {
                "background": background,
                "foreground": foreground,
                "muted": muted,
                "muted_contrast": round(contrast(muted, background), 2),
                "minimum": MIN_MUTED_CONTRAST,
            }
        )
    )


if __name__ == "__main__":
    main()
